sudo: required

dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "10"

install:
  - npm install

script:
  - npm run lint
  - npm run test-ci
  - npm run e2e
  - npm run build-prod

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

deploy:
  on:
    branch: develop
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist

notifications:
  email:
    on_failure: change
    on_success: change
